apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        server_name localhost;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /health {
          return 200 'OK';
          add_header Content-Type text/plain;
        }
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Kubernetes Basics Project</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
      </style>
    </head>
    <body>
      <h1>this page works? :D</h1>
    </body>
    </html>