apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes Basics</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
      </style>
    </head>
    <body>
      <h1>Welcome to my kubernetes basics project</h1>
      <p>I made this just to showcase my basic knowledge of kubernetes.<br> Try the /health endpoint for a status check :D</p>
    </body>
    </html>